name: 'uv version bump'
author: Dominique Rehborn
description: 'Bump version with uv and git tag'
branding:
  icon: chevron-up
  color: blue


inputs:
  bump:
    description: Version Bump (major, minor, patch + alpha, beta, rc, post, and dev, ie "minor dev")
    required: false
    default: 'minor'
  github_token:
    description: github token for updating pyproject.toml and uv.lock and pushing version as tag
    required: true


outputs:
  VERSION:
    description: "VERSION"
    value: "${{ steps.version.outputs.VERSION }}"

runs:
  using: "composite"
  steps:
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "latest"

    - name: Version Bump
      id: version
      shell: bash
      run: |
        OLD_VERSION=$(uv version --short)
        uv version $(for bump in ${{ inputs.bump }}; do echo -n "--bump $bump "; done)
        uv lock
        VERSION=$(uv version --short)
  
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git remote set-url origin https://git:${{ inputs.github_token }}@github.com/${{ github.repository }}
  
        git add pyproject.toml uv.lock
        git commit -m "bump to version ${VERSION}"
        git push origin main
  
        git tag -a ${VERSION} -m "version ${VERSION}"
        git push origin tag ${VERSION}
  
        echo "VERSION BUMP: ${OLD_VERSION} -> ${VERSION}"
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
